# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1aaef7c5ca60daca2ede56710a312a3233ddc4f6ae32520154906153e1f7347d54fa4a7111c88420dc37ef6e3afc947bf5dfe5704fd8d5bda320224389b6278

test:
  secret_key_base: e54fef3730c313933e5591fb5036eac52eac5ed1580a73c289b365ca0052ce11403e8d7c4e29a3269360a8e7a8023ddd36b836be4926b5c496203f1ee2ec400c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
